apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortener-deployment
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: urlshortener
  template:
    metadata:
      labels:
        app: urlshortener
    spec:
      containers:
      - name: urlshortener-app
        image: urlshortener-app:latest  # Update with your Docker image name and tag
        ports:
        - containerPort: 8000
